### ISSUE TITLE
Larger 'hit' areas for buttons

### ISSUE THREAD

**Issue by jonoden** [DoomOwl/TigerNine#6]
I think Alex might have gotten to this already.

**Comment by maxdumas** [comment]
@ibrews can you confirm? I'll run through the buttons myself and see if any of them have too small box colliders myself, also.

**Comment by maxdumas** [comment]
Yeah this wasn't fixed; ButtonDefault especially had a really tiny collider. I adjusted them all to be much easier to hit as of 46b619a7af47cc43e49e67d51670e30af59a6a18. Reopen if anyone feels they are still too small.

**Comment by ibrews** [comment]
Yeah the only one I adjusted was the plug. Good job Max
